@startuml
' --- Paramètres esthétiques ---
skinparam shadowing true
skinparam roundcorner 10
skinparam nodesep 20
skinparam ranksep 20
skinparam class {
    BackgroundColor White
    ArrowColor #263238
    BorderColor #263238
}

package core {

    interface Language {
      + class: Class
      + attribute: Attribute
      + method: Method
      + enum: Enum
      + interface: Interface
      + dependency: Dependency 
      + agregation: Agregation 
      + extension: Extension 
      + composition: Composition 
    }

    abstract class CodableElement {
        - comment: String
        + toCode(): String
    }
    
    class Package {
      +toCode(): String
    }

    together {
        abstract class Class {
            - id: int
            - name: String
            - isAbstract: boolean
            - fileName: String
            + setId(id: int): void
            + setName(name: String): void
            + setAbstract(isAbstract: boolean): void
            + setFilename(name: String): void
            + addAttribute(attr: Attribute): void
            + addMethod(meth: Method): void
        }

        abstract class Method {
            - name: String
            - visibility: accessSpecifier
            - parameters: String[]
            - returnType: String
            + setName(name: String): void
            + setVisibility(vis: accessSpecifier): void
            + setParameters(p: String[]): void
            + setReturnType(type: String): void
        }

        abstract class Attribute {
            - name: String
            - type: String
            - visibility: accessSpecifier
            + setName(name: String): void
            + setType(type: String): void
            + setVisibility(vis: accessSpecifier): void
        }
        
        abstract class Enum {
          - name: String
          - filename: String
          - elements: String[]
          +setName(name: String): void
          +setFilename(name: String): void
          +setElements(elements: String[]): void
        }
        
    }

    enum accessSpecifier {
        PUBLIC
        PRIVATE
        PROTECTED
    }

    abstract class ClassDiagram {
      + toCode(): String
    }

    abstract class Relation {
        - sementics: String
        + setSource(source: Class): void
        + setDestination(destination: Class): void
        + setSemantics(text: String): void
    }

    abstract class CardinalityRelation extends Relation {
        - sourceRole: String
        - sourceCardinality: String
        - destinationRole: String
        - destinationCardinality: String
        + setSourceRole(role: String): void
        + setSourceCardinality(cap: String): void
        + setDestinationRole(role: String): void
        + setDestinationCardinality(cap: String): void
    }

    together {
        abstract class Generalization extends Relation
        abstract class Association extends Relation
        abstract class Implementation extends Relation
        abstract class Agregation extends CardinalityRelation
        abstract class Composition extends CardinalityRelation
    }

    abstract class Note {
        - body
        + setBody(text: String): void
        + setTarget(target: Class): void
    }

    abstract class Interface extends Class

    ' --- Relations et Mise en page ---

    Class -up-|> CodableElement
    Method -up-|> CodableElement
    Attribute -up-|> CodableElement
    Relation -up-|> CodableElement
    Note -up-|> CodableElement
    Enum -up-|> CodableElement

    ' Organisation interne de Class
    Attribute "*" --* "1" Class : possède <
    Method "*" --* "1" Class : possède <


    Relation "*" --> "2" Class : (source, destination) > 

    ClassDiagram "1" o-- "*" Package
    Package "1" o-- "*" CodableElement


    
    Note -- CodableElement : target >

    note left of CodableElement : Les classes qui implémentent\ncette interface peuvent être\nconverties en code.
    note right of Package : Pour le moment, il n'y a qu'un seul\n Package par diagramme. Cette classe \n est là pour prévoir les potentielles \n améliorations futures.
}

' Classes concrètes
package JavaClassDiagram {
class Java implements core.Language
class JavaClass 
class JavaAttribute 
class JavaMethod 
class JavaInterface 
class JavaDependency 
class JavaAgregation 
class JavaExtension 
class JavaComposition 

}
package CppClassDiagram {
class Cpp implements core.Language
class CppClass 
class CppAttribute 
class CppMethod 
class CppInterface 
class CppDependency 
class CppAgregation 
class CppExtension 
class CppComposition 

}
package PythonClassDiagram {
class Python implements core.Language
class PythonClass 
class PythonAttribute 
class PythonMethod 
class PythonInterface 
class PythonDependency 
class PythonAgregation 
class PythonExtension 
class PythonComposition 


}

JavaClassDiagram --+ core
CppClassDiagram --+ core
PythonClassDiagram --+ core






@enduml