@startuml

interface Codable {
 + toCode(): String
}

abstract class ClassDiagram {
  - elements: List
  + setElements(elements: List): void

}

abstract class Relation {
  - source: Class
  - destination: Class
  - role: String

  + setSource(source: Class): void
  + setDestination(destination: Class): void

}

abstract class CardinalityRelation extends Relation {
  - sourceCardinality: String
  - destinationCardinality: String
  + setSourceCardinality(cap: String): void
  + setDestinationCardinality(cap: String): void
  
}



abstract class Generalization extends Relation {}
abstract class Association extends Relation {}
abstract class Agregation extends CardinalityRelation {}
abstract class Composition extends CardinalityRelation {}
abstract class Implementation extends Relation {}

abstract class Class {
  - id: int
  - name: String
  - isAbstract: boolean
  
  + setId(id: int): void
  + setName(name: String): void
  + setAbstract(isAbstract: boolean): void
  + addAttribute(attr: Attribute): void
  + addMethod(meth: Method): void

}

abstract class Method {
  - name: String
  - visibility: accessSpecifier
  - parameters: String[]
  - returnType: String
  
  + setName(name: String): void
  + setVisibility(vis: accessSpecifier): void
  + setParameters(p: String[]): void
  + setReturnType(type: String): void

}

abstract class Attribute {
  - name: String
  - type: String
  - visibility: accessSpecifier
  
  + setName(name: String): void
  + setType(type: String): void
  + setVisibility(vis: accessSpecifier): void

}

abstract class Note {
  - body
  
}

abstract class Interface extends Class {}

enum accessSpecifier {
  PUBLIC
  PRIVATE
  PROTECTED
}

' Relations
Attribute "*" --* "1" Class : possède <
Method "*" --* "1" Class : possède <

Relation "*" --* "1" Class : source
Relation "*" --* "1" Class : destination
Class --o Relation : f


ClassDiagram "*" o-- "*" Class

ClassDiagram ..|> Codable
Class ..|> Codable
Method ..|> Codable
Attribute ..|> Codable
Relation ..|> Codable
Note ..|> Codable

@enduml