@startuml

abstract class Language {
  #elements
  +toCode()
}

abstract class Relation {
  +Class source
  +Class destination
  +str sourceCardinality
  +str destinationCardinality
  +toCode()
}

abstract class Extension {

}
abstract class Dependency {}
abstract class Agregation {}
abstract class Composition {}

abstract class Class {
  -int id
  -str name
  -bool abstract
  +setName(str)
  +setAbstract(bool)
  +addAttribute(Attribute)
  +addMethod(Method)
  +toCode()
}

abstract class Method {
  +str name
  +accessSpecifier
  +str parameters[]
  +str returnType
  +toCode()
}

abstract class Attribute {
  +accessSpecifier
  +str type
  +str name
  +toCode()
}

abstract class Interface {
}

enum accessSpecifier {
  PUBLIC
  PRIVATE
  PROTECTED
}

Interface --|> Class

Attribute "*" --* "1" Class : < possède
Method "*" --* "1" Class : < possède
Interface "*" --o "*" Class : implémente <
Class "*" --> "1" Class : Spécialise

Relation <|-- Extension
Relation <|-- Dependency
Relation <|-- Agregation
Relation <|-- Composition


Language o-- Relation
Language o-- Class

@enduml